// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID            int64
	Season        int16
	GameDate      pgtype.Date
	HomeTeamID    int64
	VisitorTeamID int64
	HomeScore     *int16
	VisitorScore  *int16
	Status        string
	Postseason    bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Player struct {
	ID        int64
	FirstName string
	LastName  string
	Position  *string
	HeightCm  *int16
	TeamID    *int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Season struct {
	Year int16
}

type Team struct {
	ID           int64
	Name         string
	City         string
	Abbreviation string
	Conference   string
	Division     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
