// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
)

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, city, abbreviation, conference, division
FROM teams
WHERE id = $1
`

type GetTeamByIDRow struct {
	ID           int64
	Name         string
	City         string
	Abbreviation string
	Conference   string
	Division     string
}

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (GetTeamByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i GetTeamByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Abbreviation,
		&i.Conference,
		&i.Division,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, city, abbreviation, conference, division
FROM teams
WHERE $1::text IS NULL
   OR conference = $1::text
ORDER BY city, name
`

type ListTeamsRow struct {
	ID           int64
	Name         string
	City         string
	Abbreviation string
	Conference   string
	Division     string
}

// Returns every team, optionally filtered by conference ('East' or 'West').
func (q *Queries) ListTeams(ctx context.Context, conference *string) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, conference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Abbreviation,
			&i.Conference,
			&i.Division,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTeam = `-- name: UpsertTeam :exec
INSERT INTO teams (id, name, city, abbreviation, conference, division)
VALUES ($1, $2, $3, $4, $5, $6)
    ON CONFLICT (id) DO UPDATE SET
    name         = EXCLUDED.name,
                            city         = EXCLUDED.city,
                            abbreviation = EXCLUDED.abbreviation,
                            conference   = EXCLUDED.conference,
                            division     = EXCLUDED.division,
                            updated_at   = now()
`

type UpsertTeamParams struct {
	ID           int64
	Name         string
	City         string
	Abbreviation string
	Conference   string
	Division     string
}

// Inserts a team or, if the id already exists, updates it.
func (q *Queries) UpsertTeam(ctx context.Context, arg UpsertTeamParams) error {
	_, err := q.db.Exec(ctx, upsertTeam,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Abbreviation,
		arg.Conference,
		arg.Division,
	)
	return err
}
